<?php

$mapping = array(
    'Aws\Api\AbstractModel' => __DIR__ . '/Aws/Api/AbstractModel.php',
    'Aws\Api\ApiProvider' => __DIR__ . '/Aws/Api/ApiProvider.php',
    'Aws\Api\ErrorParser\XmlErrorParser' => __DIR__ . '/Aws/Api/ErrorParser/XmlErrorParser.php',
    'Aws\Api\Operation' => __DIR__ . '/Aws/Api/Operation.php',
    'Aws\Api\Parser\AbstractParser' => __DIR__ . '/Aws/Api/Parser/AbstractParser.php',
    'Aws\Api\Parser\AbstractRestParser' => __DIR__ . '/Aws/Api/Parser/AbstractRestParser.php',
    'Aws\Api\Parser\PayloadParserTrait' => __DIR__ . '/Aws/Api/Parser/PayloadParserTrait.php',
    'Aws\Api\Parser\RestXmlParser' => __DIR__ . '/Aws/Api/Parser/RestXmlParser.php',
    'Aws\Api\Parser\XmlParser' => __DIR__ . '/Aws/Api/Parser/XmlParser.php',
    'Aws\Api\Serializer\RestSerializer' => __DIR__ . '/Aws/Api/Serializer/RestSerializer.php',
    'Aws\Api\Serializer\RestXmlSerializer' => __DIR__ . '/Aws/Api/Serializer/RestXmlSerializer.php',
    'Aws\Api\Serializer\XmlBody' => __DIR__ . '/Aws/Api/Serializer/XmlBody.php',
    'Aws\Api\Service' => __DIR__ . '/Aws/Api/Service.php',
    'Aws\Api\Shape' => __DIR__ . '/Aws/Api/Shape.php',
    'Aws\Api\ShapeMap' => __DIR__ . '/Aws/Api/ShapeMap.php',
    'Aws\Api\StructureShape' => __DIR__ . '/Aws/Api/StructureShape.php',
    'Aws\Api\TimestampShape' => __DIR__ . '/Aws/Api/TimestampShape.php',
    'Aws\Api\Validator' => __DIR__ . '/Aws/Api/Validator.php',
    'Aws\AwsClient' => __DIR__ . '/Aws/AwsClient.php',
    'Aws\AwsClientInterface' => __DIR__ . '/Aws/AwsClientInterface.php',
    'Aws\AwsClientTrait' => __DIR__ . '/Aws/AwsClientTrait.php',
    'Aws\ClientResolver' => __DIR__ . '/Aws/ClientResolver.php',
    'Aws\Command' => __DIR__ . '/Aws/Command.php',
    'Aws\CommandInterface' => __DIR__ . '/Aws/CommandInterface.php',
    'Aws\Credentials\CredentialProvider' => __DIR__ . '/Aws/Credentials/CredentialProvider.php',
    'Aws\Credentials\Credentials' => __DIR__ . '/Aws/Credentials/Credentials.php',
    'Aws\Credentials\CredentialsInterface' => __DIR__ . '/Aws/Credentials/CredentialsInterface.php',
    'Aws\Endpoint\EndpointProvider' => __DIR__ . '/Aws/Endpoint/EndpointProvider.php',
    'Aws\Endpoint\Partition' => __DIR__ . '/Aws/Endpoint/Partition.php',
    'Aws\Endpoint\PartitionEndpointProvider' => __DIR__ . '/Aws/Endpoint/PartitionEndpointProvider.php',
    'Aws\Endpoint\PartitionInterface' => __DIR__ . '/Aws/Endpoint/PartitionInterface.php',
    'Aws\Exception\UnresolvedApiException' => __DIR__ . '/Aws/Exception/UnresolvedApiException.php',
    'Aws\Handler\GuzzleV6\GuzzleHandler' => __DIR__ . '/Aws/Handler/GuzzleV6/GuzzleHandler.php',
    'Aws\HandlerList' => __DIR__ . '/Aws/HandlerList.php',
    'Aws\HasDataTrait' => __DIR__ . '/Aws/HasDataTrait.php',
    'Aws\Middleware' => __DIR__ . '/Aws/Middleware.php',
    'Aws\Result' => __DIR__ . '/Aws/Result.php',
    'Aws\ResultInterface' => __DIR__ . '/Aws/ResultInterface.php',
    'Aws\RetryMiddleware' => __DIR__ . '/Aws/RetryMiddleware.php',
    'Aws\S3\AccelerateMiddleware' => __DIR__ . '/Aws/S3/AccelerateMiddleware.php',
    'Aws\S3\AmbiguousSuccessParser' => __DIR__ . '/Aws/S3/AmbiguousSuccessParser.php',
    'Aws\S3\ApplyChecksumMiddleware' => __DIR__ . '/Aws/S3/ApplyChecksumMiddleware.php',
    'Aws\S3\GetBucketLocationParser' => __DIR__ . '/Aws/S3/GetBucketLocationParser.php',
    'Aws\S3\PermanentRedirectMiddleware' => __DIR__ . '/Aws/S3/PermanentRedirectMiddleware.php',
    'Aws\S3\PutObjectUrlMiddleware' => __DIR__ . '/Aws/S3/PutObjectUrlMiddleware.php',
    'Aws\S3\RetryableMalformedResponseParser' => __DIR__ . '/Aws/S3/RetryableMalformedResponseParser.php',
    'Aws\S3\S3Client' => __DIR__ . '/Aws/S3/S3Client.php',
    'Aws\S3\S3ClientInterface' => __DIR__ . '/Aws/S3/S3ClientInterface.php',
    'Aws\S3\S3ClientTrait' => __DIR__ . '/Aws/S3/S3ClientTrait.php',
    'Aws\S3\S3MultiRegionClient' => __DIR__ . '/Aws/S3/S3MultiRegionClient.php',
    'Aws\S3\SSECMiddleware' => __DIR__ . '/Aws/S3/SSECMiddleware.php',
    'Aws\Sdk' => __DIR__ . '/Aws/Sdk.php',
    'Aws\Signature\S3SignatureV4' => __DIR__ . '/Aws/Signature/S3SignatureV4.php',
    'Aws\Signature\SignatureInterface' => __DIR__ . '/Aws/Signature/SignatureInterface.php',
    'Aws\Signature\SignatureProvider' => __DIR__ . '/Aws/Signature/SignatureProvider.php',
    'Aws\Signature\SignatureTrait' => __DIR__ . '/Aws/Signature/SignatureTrait.php',
    'Aws\Signature\SignatureV4' => __DIR__ . '/Aws/Signature/SignatureV4.php',
    'Aws\WrappedHttpHandler' => __DIR__ . '/Aws/WrappedHttpHandler.php',
    'GuzzleHttp\Client' => __DIR__ . '/GuzzleHttp/Client.php',
    'GuzzleHttp\ClientInterface' => __DIR__ . '/GuzzleHttp/ClientInterface.php',
    'GuzzleHttp\Exception\ClientException' => __DIR__ . '/GuzzleHttp/Exception/ClientException.php',
    'GuzzleHttp\Handler\CurlFactory' => __DIR__ . '/GuzzleHttp/Handler/CurlFactory.php',
    'GuzzleHttp\Handler\CurlFactoryInterface' => __DIR__ . '/GuzzleHttp/Handler/CurlFactoryInterface.php',
    'GuzzleHttp\Handler\CurlHandler' => __DIR__ . '/GuzzleHttp/Handler/CurlHandler.php',
    'GuzzleHttp\Handler\CurlMultiHandler' => __DIR__ . '/GuzzleHttp/Handler/CurlMultiHandler.php',
    'GuzzleHttp\Handler\Proxy' => __DIR__ . '/GuzzleHttp/Handler/Proxy.php',
    'GuzzleHttp\Handler\StreamHandler' => __DIR__ . '/GuzzleHttp/Handler/StreamHandler.php',
    'GuzzleHttp\HandlerStack' => __DIR__ . '/GuzzleHttp/HandlerStack.php',
    'GuzzleHttp\Middleware' => __DIR__ . '/GuzzleHttp/Middleware.php',
    'GuzzleHttp\Promise\FulfilledPromise' => __DIR__ . '/GuzzleHttp/Promise/FulfilledPromise.php',
    'GuzzleHttp\Promise\Promise' => __DIR__ . '/GuzzleHttp/Promise/Promise.php',
    'GuzzleHttp\Promise\PromiseInterface' => __DIR__ . '/GuzzleHttp/Promise/PromiseInterface.php',
    'GuzzleHttp\Promise\TaskQueue' => __DIR__ . '/GuzzleHttp/Promise/TaskQueue.php',
    'GuzzleHttp\Psr7\LazyOpenStream' => __DIR__ . '/GuzzleHttp/Psr7/LazyOpenStream.php',
    'GuzzleHttp\Psr7\MessageTrait' => __DIR__ . '/GuzzleHttp/Psr7/MessageTrait.php',
    'GuzzleHttp\Psr7\Request' => __DIR__ . '/GuzzleHttp/Psr7/Request.php',
    'GuzzleHttp\Psr7\Stream' => __DIR__ . '/GuzzleHttp/Psr7/Stream.php',
    'GuzzleHttp\Psr7\Uri' => __DIR__ . '/GuzzleHttp/Psr7/Uri.php',
    'GuzzleHttp\RedirectMiddleware' => __DIR__ . '/GuzzleHttp/RedirectMiddleware.php',
    'Psr\Http\Message\MessageInterface' => __DIR__ . '/Psr/Http/Message/MessageInterface.php',
    'Psr\Http\Message\RequestInterface' => __DIR__ . '/Psr/Http/Message/RequestInterface.php',
    'Psr\Http\Message\StreamInterface' => __DIR__ . '/Psr/Http/Message/StreamInterface.php',
    'Psr\Http\Message\UriInterface' => __DIR__ . '/Psr/Http/Message/UriInterface.php',
);

spl_autoload_register(function ($class) use ($mapping) {
    if (isset($mapping[$class])) {
        require $mapping[$class];
    }
}, true);

require __DIR__ . '/Aws/functions.php';
require __DIR__ . '/GuzzleHttp/functions.php';
require __DIR__ . '/GuzzleHttp/Psr7/functions.php';
require __DIR__ . '/GuzzleHttp/Promise/functions.php';
require __DIR__ . '/JmesPath/JmesPath.php';
